---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: reloader
  namespace: stakater
spec:
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  releaseName: reloader
  interval: 5m
  timeout: 15m
  chart:
    spec:
      chart: "reloader"
      version: v1.0.23
      sourceRef:
        kind: HelmRepository
        name: reloader
        namespace: flux-system
  values:
    reloader:
        resources:
          limits:
            cpu: 250m
            memory: 250Mi
          requests:
            cpu: 250m
            memory: 250Mi