---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: releases
  namespace: flux-system
spec:
  interval: 5m0s
  ref:
    branch: main
  secretRef:
    name: releases
  url: ssh://git@github.com/Improwised/flux-starter-kit
