---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: releases
  namespace: flux-system
stringData:
  identity: |
    -----BEGIN PRIVATE KEY-----
    MIG2AgEAMBAGByqGSM49AgEGBSuBBAAiBIGeMIGbAgEBBDCfjBAYbp64Q/yd6vfD
    aHkp5TRCcqt5jCZvuPM/1o06l1L8krUSYNnY3jgvHFvcVjahZANiAARv6ycwTGk3
    xGC8aEOLncbjDSY3K/hOrNH9gx0XXPp+U8hQYQqpDsDfgTK0159LQGIS39vrGUI3
    6P2ZAAs4t7FleLczCIqrtKjjO6B4IJZFrK8EgPUizC9h0seAfFVRL3w=
    -----END PRIVATE KEY-----
  identity.pub: |
    ecdsa-sha2-nistp384 AAAAE2VjZHNhLXNoYTItbmlzdHAzODQAAAAIbmlzdHAzODQAAABhBG/rJzBMaTfEYLxoQ4udxuMNJjcr+E6s0f2DHRdc+n5TyFBhCqkOwN+BMrTXn0tAYhLf2+sZQjfo/ZkACzi3sWV4tzMIiqu0qOM7oHgglkWsrwSA9SLML2HSx4B8VVEvfA==
  known_hosts: github.com ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBEmKSENjQEezOmxkZMy7opKgwFB9nkt5YRrYMjNuG5N87uRgg6CLrbo5wAdT/y6v0mKV0U2w0WZ2YB/++Tpockg=
